version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      #- browser-tools/install-browser-tools:
      #    chrome-version: 127.0.6533.99
      - run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | $SUDO apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          wget --no-verbose -O /tmp/chrome.deb "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_127.0.6533.99-1_amd64.deb" \
            && $SUDO apt-get install -y /tmp/chrome.deb \
            && rm /tmp/chrome.deb



