version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: 127.0.6533.99-1
