version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      #- browser-tools/install-browser-tools:
      #    chrome-version: 127.0.6533.99
      - run: |
          curl https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_127.0.6533.99-1_amd64.deb -o google-chrome-stable.deb \
            && dpkg -i google-chrome-stable.deb \
            && rm google-chrome-stable.deb \
            && google-chrome --version



